### ISSUE TITLE
Deprecate in favor of broccoli-funnel

### ISSUE THREAD

**Issue by fredrikekelund** [zeppelin/broccoli-rename-files#3]
Hey @zeppelin, quite the turnaround on my part here – going from reviving a module to wanting to deprecate it, but I realised that [broccoli-funnel](https://github.com/broccolijs/broccoli-funnel) seems to in fact support the same use case as broccoli-rename-files.

They have the `getDestinationPath` option, which lets you specify a function to be called for each file in the tree, that customizes the output paths.

It might make sense to point people in that direction instead? The Broccoli core team has already deprecated [broccoli-file-mover](https://github.com/rjackson/broccoli-file-mover) in favor of broccoli-funnel.

**Comment by zeppelin** [comment]
I'm in favor. Merged your PR, thanks!

**Comment by fredrikekelund** [comment]
Thanks for merging the PR! I think the Broccoli community benefits from clarity around current best practices :+1:

Would probably be good with a 1.0.1 release as well just to get the updated README out to npm as well
